apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    traefik.enable: "false"
  creationTimestamp: null
  name: mongo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
        traefik.enable: "false"
      creationTimestamp: null
      labels:
        app: mongo
    spec:
      containers:
        - args:
            - mongod
            - --smallfiles
            - --oplogSize
            - "128"
            - --replSet
            - rs0
            - --storageEngine=mmapv1
          image: mongo:4.0
          name: mongo
          resources: {}
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: mongo-claim0
      restartPolicy: Always
      volumes:
        - name: mongo-claim0
          persistentVolumeClaim:
            claimName: mongo-claim0
status: {}
