apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
    traefik.backend: rocketchat
    traefik.frontend.rule: 'Host: your.domain.tld'
  creationTimestamp: null
  labels:
    io.kompose.service: rocketchat
  name: rocketchat
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: rocketchat
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
        traefik.backend: rocketchat
        traefik.frontend.rule: 'Host: 34.146.143.246:3000'
      creationTimestamp: null
      labels:
        io.kompose.service: rocketchat
    spec:
      containers:
        - args:
            - bash
            - -c
            - |-
              for i in `seq 1 30`; do
                  node main.js &&
                  s=$? && break || s=$?;
                  echo "Tried $i times. Waiting 5 secs...";
                  sleep 5;
                done; (exit $s)
          env:
            - name: MAIL_URL
              value: smtp://smtp.email
            - name: MONGO_OPLOG_URL
              value: mongodb://mongo:27017/local
            - name: MONGO_URL
              value: mongodb://mongo:27017/rocketchat
            - name: PORT
              value: "3000"
            - name: ROOT_URL
              value: http://34.146.143.246:3000
          image: registry.rocket.chat/rocketchat/rocket.chat:latest
          name: rocketchat
          ports:
            - containerPort: 3000
          resources: {}
          volumeMounts:
            - mountPath: /app/uploads
              name: rocketchat-claim0
      restartPolicy: Always
      volumes:
        - name: rocketchat-claim0
          persistentVolumeClaim:
            claimName: rocketchat-claim0
status: {}
